apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ui
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
