apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev
  labels:
    app: quantumvestai
    component: application
    environment: dev
type: Opaque
data:
  JWT_SECRET: e6kke6hxSVAF5DBiiLb7oD7uQIjG40DLL2QnTKu8uw4=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: YWRtaW4=
  ADMIN_EMAIL: ZGFwYXJ0aGkuZ2F5YXRyaUBnbWFpbC5jb20=
  ALPHA_VANTAGE_API_KEY: YWxwaGEtdGVzdA==
  RAPIDAPI_KEY: MjVhOTc4MTE3OG1zaDQ1ZjkyODllZWVlYzE4MXAxNDEwZGZqc25jMzFlMmFmMjE5Mzc=
---
apiVersion: v1
kind: Secret
metadata:
  name: twitter-secrets
  namespace: dev
  labels:
    app: quantumvestai
    component: twitter
    environment: dev
type: Opaque
data:
  TWITTER_CONSUMER_KEY: YVhLWGxVcHVidDNRQ3piM0tITm5PVVBibw==
  TWITTER_CONSUMER_SECRET: aVdFZlV6YU85TmJWT0lXNk05M2ZBZkFSTWJ2cTJrd2VmdVp6aDYzMUF6bXFLdFIwZTA=
  TWITTER_ACCESS_TOKEN: MTkxOTU4NjU1ODY2OTQyMjU5Mi16QkpQVGVLYW9xaVgxTjUyM1liWFJHR25QcWJjZnc=
  TWITTER_ACCESS_SECRET: STlIODkzbm1sRkpzdkwwWXVNdFYweHpKN0FYbG1LUEVYNHlXWkpSb1Fad2Vl
---
apiVersion: v1
kind: Secret
metadata:
  name: quantumvestai-cluster-rds-credentials
  namespace: dev
  labels:
    app: quantumvestai
    component: database
    environment: dev
type: Opaque
data:
  database: cXVhbnR1bXZlc3RhaWRi
  dbname: cXVhbnR1bXZlc3RhaWRi
  endpoint: cXVhbnR1bXZlc3RhaS1kZXYuY3dic3FzaXl3d2FhLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMy
  host: cXVhbnR1bXZlc3RhaS1kZXYuY3dic3FzaXl3d2FhLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  password: NzVMZXJLJTBfSjx0JEh9Wg==
  port: NTQzMg==
  username: ZGJhZG1pbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
  namespace: dev
  labels:
    app: quantumvestai
    component: ui
    environment: dev
type: Opaque
data:
  JWT_SECRET_KEY: e6kke6hxSVAF5DBiiLb7oD7uQIjG40DLL2QnTKu8uw4=
  YAHOO_FINANCE_API_KEY:
  TWITTER_API_KEY: YVhLWGxVcHVidDNRQ3piM0tITm5PVVBibw==
  TWITTER_API_SECRET: aVdFZlV6YU85TmJWT0lXNk05M2ZBZkFSTWJ2cTJrd2VmdVp6aDYzMUF6bXFLdFIwZTA=
  TWITTER_ACCESS_TOKEN: MTkxOTU4NjU1ODY2OTQyMjU5Mi16QkpQVGVLYW9xaVgxTjUyM1liWFJHR25QcWJjZnc=
  TWITTER_ACCESS_SECRET: STlIODkzbm1sRkpzdkwwWXVNdFYweHpKN0FYbG1LUEVYNHlXWkpSb1Fad2Vl
  ALPHA_VANTAGE_API_KEY: WkFUN1pJN0VHUzhWREEyQQ==
  RAPIDAPI_KEY: MjVhOTc4MTE3OG1zaDQ1ZjkyODllZWVlYzE4MXAxNDEwZGZqc25jMzFlMmFmMjE5Mzc=
