apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: dev
  labels:
    app: quantumvestai
    tier: api
spec:
  selector:
    app: quantumvestai
    tier: api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP