apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET: c3VwZXJzZWNyZXRrZXkxMjM0NTY3ODlhYmNkZWY=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: YWRtaW4=
  ADMIN_EMAIL: ZGFwYXJ0aGkuZ2F5YXRyaUBnbWFpbC5jb20=
  ALPHA_VANTAGE_API_KEY: TVREOUlSMjdRM0ExWlZOSA==
  RAPIDAPI_KEY: MjVhOTc4MTE3OG1zaDQ1ZjkyODllZWVlYzE4MXAxNDEwZGZqc25jMzFlMmFmMjE5Mzc=
