apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET: e6kke6hxSVAF5DBiiLb7oD7uQIjG40DLL2QnTKu8uw4=
  ADMIN_USERNAME: YWRtaW4=
  ADMIN_PASSWORD: YWRtaW4=
  ADMIN_EMAIL: ZGFwYXJ0aGkuZ2F5YXRyaUBnbWFpbC5jb20=
  ALPHA_VANTAGE_API_KEY: YWxwaGEtdGVzdA==
  RAPIDAPI_KEY: <base64-encoded-rapidapi-key>
