apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumvestai
  labels:
    app: quantumvestai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quantumvestai
  template:
    metadata:
      labels:
        app: quantumvestai
    spec:
      containers:
      - name: quantumvestai
        image: 921930869047.dkr.ecr.us-east-1.amazonaws.com/quantumvestai:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"