apiVersion: v1
data:
  database: cXVhbnR1bXZlc3RhaWRi
  endpoint: cXVhbnR1bXZlc3RhaS1kZXYuY3dic3FzaXl3d2FhLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMy
  password: NzVMZXJLJTBfSjx0JEh9Wg==
  port: NTQzMg==
  username: ZGJhZG1pbg==
kind: Secret
metadata:
  creationTimestamp: 
  name: quantumvestai-cluster-rds-credentials
  namespace: dev
  resourceVersion: 
  uid: 
type: Opaque
