apiVersion: v1
kind: Secret
metadata:
  name: quantumvestai-secrets
  labels:
    app: quantumvestai
type: Opaque
data:
  # These are base64 encoded placeholders - replace with your actual encoded secrets
  jwt-secret-key: bm5UK1NlMXpGV1NxNU1uZjh2VkZDQUViSHZBR3I4eWNhZi9CamNXZ3dzRT0=
  admin-api-key: YTQzYzYzZWY2OThkNDhkYmUzNjFiYmM3ODY4ZWIwNjM=
  twitter-bearer-token: QUFBQUFBQUFBQUFBQUFBQUFBQUFBSkV0MVFFQUFBQUE1bGNkTERpVzJXcFdCNFR2Ykg2cW5rTDlqdm8lM0RIMXlCaWN6RTRjSWtzWk9zYU13UUoxQWtpaFlKT2R5RnZYUERvSTBNdFFSUFU2NTMzUQ==