apiVersion: v1
kind: ServiceAccount
metadata:
  name: quantumvestai-sa
  namespace: NAMESPACE_PLACEHOLDER
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/quantumvestai-role