apiVersion: v1
kind: Secret
metadata:
  name: twitter-secrets
  namespace: dev
type: Opaque
data:
  TWITTER_CONSUMER_KEY: YVhLWGxVcHVidDNRQ3piM0tITm5PVVBibw==
  TWITTER_CONSUMER_SECRET: aVdFZlV6YU85TmJWT0lXNk05M2ZBZkFSTWJ2cTJrd2VmdVp6aDYzMUF6bXFLdFIwZTA=
  TWITTER_ACCESS_TOKEN: MTkxOTU4NjU1ODY2OTQyMjU5Mi16QkpQVGVLYW9xaVgxTjUyM1liWFJHR25QcWJjZnc=
  TWITTER_ACCESS_SECRET: STlIODkzbm1sRkpzdkwwWXVNdFYweHpKN0FYbG1LUEVYNHlXWkpSb1Fad2Vl