apiVersion: v1
kind: Secret
metadata:
  name: twitter-secrets
  namespace: NAMESPACE_PLACEHOLDER
type: Opaque
data:
  TWITTER_CONSUMER_KEY: ""
  TWITTER_CONSUMER_SECRET: ""
  TWITTER_ACCESS_TOKEN: ""
  TWITTER_ACCESS_SECRET: ""