apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ui-hpa
  namespace: NAMESPACE_PLACEHOLDER
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ui-deployment
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300