apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
type: Opaque
data:
  # These need to be base64 encoded
  JWT_SECRET_KEY: e6kke6hxSVAF5DBiiLb7oD7uQIjG40DLL2QnTKu8uw4=
  YAHOO_FINANCE_API_KEY:
  TWITTER_API_KEY: YVhLWGxVcHVidDNRQ3piM0tITm5PVVBibw==
  TWITTER_API_SECRET: aVdFZlV6YU85TmJWT0lXNk05M2ZBZkFSTWJ2cTJrd2VmdVp6aDYzMUF6bXFLdFIwZTA=
  TWITTER_ACCESS_TOKEN: MTkxOTU4NjU1ODY2OTQyMjU5Mi16QkpQVGVLYW9xaVgxTjUyM1liWFJHR25QcWJjZnc=
  TWITTER_ACCESS_SECRET: STlIODkzbm1sRkpzdkwwWXVNdFYweHpKN0FYbG1LUEVYNHlXWkpSb1Fad2Vl
  ALPHA_VANTAGE_API_KEY: WkFUN1pJN0VHUzhWREEyQQ==
  RAPIDAPI_KEY: <base64-encoded-rapidapi-key>
