apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
type: Opaque
data:
  # These need to be base64 encoded
  JWT_SECRET_KEY: <base64-encoded-jwt-secret>
  YAHOO_FINANCE_API_KEY: <base64-encoded-yahoo-key>
  TWITTER_API_KEY: <base64-encoded-twitter-key>
  TWITTER_API_SECRET: <base64-encoded-twitter-secret>
  TWITTER_ACCESS_TOKEN: <base64-encoded-twitter-access>
  TWITTER_ACCESS_SECRET: <base64-encoded-twitter-access-secret>