apiVersion: v1
kind: Service
metadata:
  name: ui-service
  annotations:
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
spec:
  selector:
    app: quantumvestai
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP  # ALB Ingress works best with NodePort or ClusterIP