apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: dev
  labels:
    app: quantumvestai
    tier: frontend
    environment: development
    created-by: daparthi001
    created-date: "2025-06-15"
  annotations:
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  selector:
    app: quantumvestai
    tier: frontend
    environment: development
  ports:
    - name: http
      port: 80       # The port this service exposes internally
      targetPort: 3000 # The container port your UI app listens on
      protocol: TCP
  type: ClusterIP