version: '3'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quantumvest
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_DB=quantumvestai
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=quantumvest
      - POSTGRES_PASSWORD=localdev
      - POSTGRES_DB=quantumvestai
      - POSTGRES_PORT=5432
      - USE_IAM_AUTH=false
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgres_data: