import React from 'react';

interface AIInsightsProps {
  /** Textual prediction generated by the AI model */
  prediction: string;
  /** Sentiment score in range [-1, 1] */
  sentiment: number;
  /** Additional summary or explanation */
  summary: string;
}

/**
 * Renders AI generated insights including prediction,
 * sentiment analysis and a short summary.
 */
const AIInsights: React.FC<AIInsightsProps> = ({ prediction, sentiment, summary }) => (
  <div className="ai-insights">
    <h3>AI Insights</h3>
    <p><strong>Prediction:</strong> {prediction}</p>
    <p><strong>Sentiment:</strong> {sentiment.toFixed(2)}</p>
    <p>{summary}</p>
  </div>
);

export default AIInsights;

