apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quantumvestai-staging

resources:
- ../../  # Reference the base configuration

patchesStrategicMerge:
- configmap-patch.yaml
- deployment-patch.yaml
- ingress-patch.yaml

commonLabels:
  environment: staging