version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: quantumvestai-ui:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DEBUG=true
      - API_BASE_URL=http://quantumvestai-dev-api:8000
      - ENVIRONMENT=development
      - PYTHONPATH=/app/ai-stock-platform:/app/ai-stock-platform/ui
    volumes:
      - ./ui:/app/ui
      - ./templates:/app/templates
      - ./static:/app/static
      - ./scripts:/app/scripts
    depends_on:
      - api
      
  api:
    image: quantumvestai-api:latest  # You'll need to build this separately
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DEBUG=true
      - ENVIRONMENT=development
      - DB_HOST=${RDS_HOST}
      - DB_PORT=${RDS_PORT}
      - DB_NAME=${RDS_DBNAME}
      - DB_USER=${RDS_USERNAME}
      - DB_PASSWORD=${RDS_PASSWORD}
      - PYTHONPATH=/app/ai-stock-platform:/app/ai-stock-platform/api
    depends_on:
      - db
      
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - DB_NAME=quantumvestai
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: