#!/usr/bin/env python3
"""
API Directory Structure Lister
Created: 2025-05-20 15:53:17
Author: daparthi001
"""

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Dict

def get_directory_structure(path: Path, indent: str = "", is_last: bool = True) -> List[str]:
    """Get the directory structure as a list of strings."""
    lines = []
    prefix = "└── " if is_last else "├── "
    lines.append(f"{indent}{prefix}{path.name}")
    
    if path.is_dir():
        # Get all items in directory
        items = list(path.iterdir())
        # Sort directories first, then files
        items.sort(key=lambda x: (not x.is_dir(), x.name.lower()))
        
        for i, item in enumerate(items):
            is_last_item = i == len(items) - 1
            new_indent = indent + ("    " if is_last else "│   ")
            lines.extend(get_directory_structure(item, new_indent, is_last_item))
    
    return lines

def get_file_info(path: Path) -> Dict:
    """Get file information."""
    stat = path.stat()
    return {
        "size": stat.st_size,
        "modified": datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S"),
        "type": "directory" if path.is_dir() else "file"
    }

def find_api_directory() -> Path:
    """Find the API directory by traversing up from the current directory."""
    current_dir = Path.cwd()
    
    # Try to find 'api' directory in current or parent directories
    while current_dir.parent != current_dir:
        # Check if we're in the api directory
        if current_dir.name == "api":
            return current_dir
        
        # Check if api directory exists in current directory
        api_dir = current_dir / "api"
        if api_dir.exists() and api_dir.is_dir():
            return api_dir
        
        # Move up one directory
        current_dir = current_dir.parent
    
    raise FileNotFoundError("Could not find api directory")

def main():
    """Main function to list API directory structure."""
    try:
        # Find the api directory
        api_dir = find_api_directory()
        
        # Print header
        print("=" * 80)
        print(f"API Directory Structure")
        print(f"Generated: 2025-05-20 15:53:17")
        print(f"Generated by: daparthi001")
        print(f"API Directory: {api_dir}")
        print("=" * 80)
        
        # Get and print directory structure
        structure = get_directory_structure(api_dir, "", True)
        print("\nDirectory Tree:")
        print("-" * 80)
        for line in structure:
            print(line)
        
        # Print summary
        print("\nSummary:")
        print("-" * 80)
        
        # Count files and directories
        total_files = 0
        total_dirs = 0
        dir_sizes = {}
        python_files = 0
        
        for item in api_dir.rglob("*"):
            try:
                if item.is_file():
                    total_files += 1
                    if item.suffix == '.py':
                        python_files += 1
                    parent = item.relative_to(api_dir).parent
                    dir_sizes[parent] = dir_sizes.get(parent, 0) + item.stat().st_size
                elif item.is_dir():
                    total_dirs += 1
            except PermissionError:
                continue
        
        print(f"Total Directories: {total_dirs}")
        print(f"Total Files: {total_files}")
        print(f"Python Files: {python_files}")
        
        # Print size by directory
        print("\nSize by Directory:")
        print("-" * 80)
        for directory, size in sorted(dir_sizes.items()):
            size_kb = size / 1024
            print(f"{directory}: {size_kb:.2f} KB")

    except FileNotFoundError as e:
        print(f"Error: {e}")
        print(f"Current directory: {Path.cwd()}")
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()