"""
Kubernetes ConfigMap
Created: 2025-05-19 05:41:48
Author: daparthi001
"""
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: quantumvest
data:
  PROJECT_NAME: "QuantumVestAI"
  VERSION: "1.0.0"
  API_V1_STR: "/api/v1"
  POSTGRES_PORT: "5432"
  BACKEND_CORS_ORIGINS: "http://localhost:3000,https://app.quantumvest.ai"