apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumvestai-redis
  namespace: quantumvestai
  labels:
    app: quantumvestai-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quantumvestai-redis
  template:
    metadata:
      labels:
        app: quantumvestai-redis
    spec:
      containers:
      - name: redis
        image: redis:6-alpine
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: quantumvestai-redis-pvc