apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quantumvestai-redis-pvc
  namespace: quantumvestai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo